name: CI/Docker

on:
    push:
        branches:
        - main

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest

        steps:
        - name: 🤓 Set image name
          run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        - name: 🐳 Login to GitHub Container Registry
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 🐳 Build and Push
          uses: docker/build-push-action@v6.10.0
          with:
            provenance: false
            platforms: linux/amd64
            push: true
            pull: true
            tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest , ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}